import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
export const dynamic = "force-dynamic";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dracula">
      <body
        className={`${inter.className} flex items-center justify-center h-screen w-screen`}
      >
        <Link href="/" className="link absolute top-2 left-2">
          torna alla home page
        </Link>
        {children}
      </body>
    </html>
  );
}
